version: '3'

services:
    python:
        image: python:3.9
        volumes:
            - ./portfolio:/portfolio
            - ./portfolio:/base
        ports:
            - 8000:8000
        command: bash -c "cd ./portfolio && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"