# Generated by Django 3.1.3 on 2021-06-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210623_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='sorting',
            new_name='date_created',
        ),
    ]
